/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siakkam;

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class ajukanJadwal extends javax.swing.JFrame {
    java.sql.Connection koneksi;
    java.sql.PreparedStatement pst;
    java.sql.Statement stmt;
    java.sql.ResultSet rs;
    javax.swing.JFrame parent;
    String username;
    String namaLembaga;
    int idLembaga;
    
    /**
     * Creates new form Mengajukan_jadwal
     */
    public ajukanJadwal(javax.swing.JFrame parent, String username) {
        this.username = username;
        this.parent = parent;
        initComponents();
        
        koneksi = dataBase.KoneksiDB.ConnectDB();
        pst = null;
        rs = null;
        stmt = null;
        
        String username_;
        try{
            pst = koneksi.prepareStatement("select a.id, a.nama, b.username from "
                    + "daftarlembaga a, "
                    + "daftarakun b "
                    + "where "
                    + "a.username = b.username and "
                    + "a.username = '"+username+"';");
            rs = pst.executeQuery();
            
            if(rs.next()){
                idLembaga = rs.getInt("id");
                namaLembaga = rs.getString("nama");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        this.setTitle(namaLembaga +" Mengajukan Jadwal");
        this.setSize(600, 500);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
        mulaiTgl.setDate(new java.util.Date());
        selesaiTgl.setDate(new java.util.Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pengajuan_kegiatan = new javax.swing.JPanel();
        Judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        List_pertanyaan = new javax.swing.JPanel();
        penyelenggara = new javax.swing.JPanel();
        namaKegiatan = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        fieldNamaKegiatan = new javax.swing.JTextField();
        tempatKegiatan = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        fieldTempatKegiatan = new javax.swing.JTextField();
        waktuMulai = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mulaiTgl = new org.jdesktop.swingx.JXDatePicker();
        mulaiJam = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        mulaiMenit = new javax.swing.JSpinner();
        waktuSelesai = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selesaiTgl = new org.jdesktop.swingx.JXDatePicker();
        selesaiJam = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        selesaiMenit = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        Pengajuan_kegiatan.setBackground(new java.awt.Color(0, 102, 102));

        Judul.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mengajukan Jadwal Kegiatan");

        javax.swing.GroupLayout JudulLayout = new javax.swing.GroupLayout(Judul);
        Judul.setLayout(JudulLayout);
        JudulLayout.setHorizontalGroup(
            JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JudulLayout.setVerticalGroup(
            JudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        Submit.setBackground(new java.awt.Color(0, 102, 102));
        Submit.setText("Kirim");
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Kembali.setBackground(new java.awt.Color(0, 102, 102));
        Kembali.setText("Kembali");
        Kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        List_pertanyaan.setBackground(new java.awt.Color(0, 153, 153));

        penyelenggara.setBackground(new java.awt.Color(0, 153, 153));

        namaKegiatan.setBackground(new java.awt.Color(0, 153, 153));

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Nama Kegiatan");

        fieldNamaKegiatan.setText("Isi nama kegiatan");
        fieldNamaKegiatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNamaKegiatanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNamaKegiatanFocusLost(evt);
            }
        });
        fieldNamaKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaKegiatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaKegiatanLayout = new javax.swing.GroupLayout(namaKegiatan);
        namaKegiatan.setLayout(namaKegiatanLayout);
        namaKegiatanLayout.setHorizontalGroup(
            namaKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKegiatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNamaKegiatan)
                .addContainerGap())
        );
        namaKegiatanLayout.setVerticalGroup(
            namaKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKegiatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldNamaKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        tempatKegiatan.setBackground(new java.awt.Color(0, 153, 153));

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Tempat Kegiatan");

        fieldTempatKegiatan.setText("Isi kode tempat kegiatan");
        fieldTempatKegiatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldTempatKegiatanFocusGained(evt);
            }
        });

        javax.swing.GroupLayout tempatKegiatanLayout = new javax.swing.GroupLayout(tempatKegiatan);
        tempatKegiatan.setLayout(tempatKegiatanLayout);
        tempatKegiatanLayout.setHorizontalGroup(
            tempatKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempatKegiatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldTempatKegiatan))
        );
        tempatKegiatanLayout.setVerticalGroup(
            tempatKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempatKegiatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tempatKegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldTempatKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        waktuMulai.setBackground(new java.awt.Color(0, 153, 153));

        label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Waktu Mulai");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal");

        mulaiJam.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        mulaiJam.setAutoscrolls(true);
        mulaiJam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mulaiJam.setName(""); // NOI18N
        mulaiJam.setOpaque(false);
        mulaiJam.setRequestFocusEnabled(false);
        mulaiJam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mulaiJamStateChanged(evt);
            }
        });
        mulaiJam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mulaiJamPropertyChange(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jam");

        mulaiMenit.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 10));
        mulaiMenit.setAutoscrolls(true);
        mulaiMenit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mulaiMenit.setName(""); // NOI18N
        mulaiMenit.setOpaque(false);
        mulaiMenit.setRequestFocusEnabled(false);
        mulaiMenit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mulaiMenitStateChanged(evt);
            }
        });
        mulaiMenit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mulaiMenitPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout waktuMulaiLayout = new javax.swing.GroupLayout(waktuMulai);
        waktuMulai.setLayout(waktuMulaiLayout);
        waktuMulaiLayout.setHorizontalGroup(
            waktuMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuMulaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mulaiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mulaiJam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mulaiMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        waktuMulaiLayout.setVerticalGroup(
            waktuMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuMulaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waktuMulaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(mulaiMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulaiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulaiJam))
                .addContainerGap())
        );

        waktuSelesai.setBackground(new java.awt.Color(0, 153, 153));

        label6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Waktu Selesai");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");

        selesaiJam.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        selesaiJam.setAutoscrolls(true);
        selesaiJam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selesaiJam.setName(""); // NOI18N
        selesaiJam.setOpaque(false);
        selesaiJam.setRequestFocusEnabled(false);
        selesaiJam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selesaiJamStateChanged(evt);
            }
        });
        selesaiJam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selesaiJamPropertyChange(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jam");

        selesaiMenit.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 10));
        selesaiMenit.setAutoscrolls(true);
        selesaiMenit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selesaiMenit.setName(""); // NOI18N
        selesaiMenit.setOpaque(false);
        selesaiMenit.setRequestFocusEnabled(false);
        selesaiMenit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selesaiMenitStateChanged(evt);
            }
        });
        selesaiMenit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selesaiMenitPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout waktuSelesaiLayout = new javax.swing.GroupLayout(waktuSelesai);
        waktuSelesai.setLayout(waktuSelesaiLayout);
        waktuSelesaiLayout.setHorizontalGroup(
            waktuSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuSelesaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selesaiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selesaiJam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selesaiMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        waktuSelesaiLayout.setVerticalGroup(
            waktuSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waktuSelesaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waktuSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(selesaiMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selesaiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selesaiJam))
                .addContainerGap())
        );

        javax.swing.GroupLayout penyelenggaraLayout = new javax.swing.GroupLayout(penyelenggara);
        penyelenggara.setLayout(penyelenggaraLayout);
        penyelenggaraLayout.setHorizontalGroup(
            penyelenggaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namaKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(waktuMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(waktuSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(penyelenggaraLayout.createSequentialGroup()
                .addComponent(tempatKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        penyelenggaraLayout.setVerticalGroup(
            penyelenggaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penyelenggaraLayout.createSequentialGroup()
                .addComponent(namaKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempatKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waktuMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waktuSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout List_pertanyaanLayout = new javax.swing.GroupLayout(List_pertanyaan);
        List_pertanyaan.setLayout(List_pertanyaanLayout);
        List_pertanyaanLayout.setHorizontalGroup(
            List_pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penyelenggara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        List_pertanyaanLayout.setVerticalGroup(
            List_pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(List_pertanyaanLayout.createSequentialGroup()
                .addComponent(penyelenggara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Pengajuan_kegiatanLayout = new javax.swing.GroupLayout(Pengajuan_kegiatan);
        Pengajuan_kegiatan.setLayout(Pengajuan_kegiatanLayout);
        Pengajuan_kegiatanLayout.setHorizontalGroup(
            Pengajuan_kegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(List_pertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pengajuan_kegiatanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        Pengajuan_kegiatanLayout.setVerticalGroup(
            Pengajuan_kegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pengajuan_kegiatanLayout.createSequentialGroup()
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(List_pertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Pengajuan_kegiatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pengajuan_kegiatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pengajuan_kegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("yyy-MM-dd");
        String nama_kegiatan, waktu_mulai, waktu_selesai, id_lembaga, id_tempat;
        nama_kegiatan = fieldNamaKegiatan.getText();
        waktu_mulai = format.format(mulaiTgl.getDate())+" "+mulaiJam.getValue().toString()+":"+mulaiMenit.getValue().toString()+":00";
        waktu_selesai = format.format(selesaiTgl.getDate())+" "+selesaiJam.getValue().toString()+":"+selesaiMenit.getValue().toString()+":00";
        id_lembaga = Integer.toString(this.idLembaga);
        id_tempat = fieldTempatKegiatan.getText();
        format = new java.text.SimpleDateFormat("yyy-MM-dd HH:mm:ss");
        String sql = "";
        
        sql = "insert into pengajuan "
                + "(waktu_diajukan, nama_kegiatan, waktu_mulai, waktu_selesai, id_lembaga, id_tempat) "
                + "values "
                + "('"+ format.format(new java.util.Date()) +"', '"+ nama_kegiatan + "', '" + waktu_mulai + "', '" + waktu_selesai + "', '"
                + id_lembaga.toUpperCase() + "', '" + id_tempat + "');";
        
        System.out.println("SQL : "+sql);
        
        try{
            stmt = koneksi.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Kueri berhasil: ");
        }catch(Exception e){
            System.out.print("Query gagal");
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void fieldNamaKegiatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaKegiatanFocusGained
        // TODO add your handling code here:
        fieldNamaKegiatan.setText("");
    }//GEN-LAST:event_fieldNamaKegiatanFocusGained

    private void fieldNamaKegiatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaKegiatanFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaKegiatanFocusLost

    private void fieldNamaKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaKegiatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaKegiatanActionPerformed

    private void fieldTempatKegiatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldTempatKegiatanFocusGained
        // TODO add your handling code here:
        fieldTempatKegiatan.setText("");
    }//GEN-LAST:event_fieldTempatKegiatanFocusGained

    private void mulaiJamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mulaiJamStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiJamStateChanged

    private void mulaiJamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mulaiJamPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_mulaiJamPropertyChange

    private void mulaiMenitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mulaiMenitStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiMenitStateChanged

    private void mulaiMenitPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mulaiMenitPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaiMenitPropertyChange

    private void selesaiJamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selesaiJamStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiJamStateChanged

    private void selesaiJamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selesaiJamPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiJamPropertyChange

    private void selesaiMenitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selesaiMenitStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiMenitStateChanged

    private void selesaiMenitPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selesaiMenitPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiMenitPropertyChange

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        
        parent.setVisible(true);
        this.dispose();
        System.out.println("Tutup Pengajuan Jadwal");
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajukanJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajukanJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajukanJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajukanJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajukanJadwal(null, "umppasa").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Judul;
    private javax.swing.JButton Kembali;
    private javax.swing.JPanel List_pertanyaan;
    private javax.swing.JPanel Pengajuan_kegiatan;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField fieldNamaKegiatan;
    private javax.swing.JTextField fieldTempatKegiatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label6;
    private javax.swing.JSpinner mulaiJam;
    private javax.swing.JSpinner mulaiMenit;
    private org.jdesktop.swingx.JXDatePicker mulaiTgl;
    private javax.swing.JPanel namaKegiatan;
    private javax.swing.JPanel penyelenggara;
    private javax.swing.JSpinner selesaiJam;
    private javax.swing.JSpinner selesaiMenit;
    private org.jdesktop.swingx.JXDatePicker selesaiTgl;
    private javax.swing.JPanel tempatKegiatan;
    private javax.swing.JPanel waktuMulai;
    private javax.swing.JPanel waktuSelesai;
    // End of variables declaration//GEN-END:variables
}
