/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siakkam;

/**
 *
 * @author Win10
 */
public class LandingTamu extends javax.swing.JFrame {

    /**
     * Creates new form LandingTamu
     */
    public LandingTamu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KalenderTamu = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        tombolMundur = new javax.swing.JPanel();
        tombolMaju = new javax.swing.JPanel();
        bulan = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        kalenderUtama = new javax.swing.JPanel();
        Senin = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        hari66 = new javax.swing.JPanel();
        tanggal66 = new javax.swing.JLabel();
        hari67 = new javax.swing.JPanel();
        tanggal67 = new javax.swing.JLabel();
        hari68 = new javax.swing.JPanel();
        tanggal68 = new javax.swing.JLabel();
        hari69 = new javax.swing.JPanel();
        tanggal69 = new javax.swing.JLabel();
        hari70 = new javax.swing.JPanel();
        tanggal70 = new javax.swing.JLabel();
        Selasa = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        hari71 = new javax.swing.JPanel();
        tanggal71 = new javax.swing.JLabel();
        hari72 = new javax.swing.JPanel();
        tanggal72 = new javax.swing.JLabel();
        hari73 = new javax.swing.JPanel();
        tanggal73 = new javax.swing.JLabel();
        hari74 = new javax.swing.JPanel();
        tanggal74 = new javax.swing.JLabel();
        hari75 = new javax.swing.JPanel();
        tanggal75 = new javax.swing.JLabel();
        Rabu = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        hari76 = new javax.swing.JPanel();
        tanggal76 = new javax.swing.JLabel();
        hari77 = new javax.swing.JPanel();
        tanggal77 = new javax.swing.JLabel();
        hari78 = new javax.swing.JPanel();
        tanggal78 = new javax.swing.JLabel();
        hari79 = new javax.swing.JPanel();
        tanggal79 = new javax.swing.JLabel();
        hari80 = new javax.swing.JPanel();
        tanggal80 = new javax.swing.JLabel();
        Kamis = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        hari81 = new javax.swing.JPanel();
        tanggal81 = new javax.swing.JLabel();
        hari82 = new javax.swing.JPanel();
        tanggal82 = new javax.swing.JLabel();
        hari83 = new javax.swing.JPanel();
        tanggal83 = new javax.swing.JLabel();
        hari84 = new javax.swing.JPanel();
        tanggal84 = new javax.swing.JLabel();
        hari85 = new javax.swing.JPanel();
        tanggal85 = new javax.swing.JLabel();
        Jumat = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        hari86 = new javax.swing.JPanel();
        tanggal86 = new javax.swing.JLabel();
        hari87 = new javax.swing.JPanel();
        tanggal87 = new javax.swing.JLabel();
        hari88 = new javax.swing.JPanel();
        tanggal88 = new javax.swing.JLabel();
        hari89 = new javax.swing.JPanel();
        tanggal89 = new javax.swing.JLabel();
        hari90 = new javax.swing.JPanel();
        tanggal90 = new javax.swing.JLabel();
        Sabtu = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        hari91 = new javax.swing.JPanel();
        tanggal91 = new javax.swing.JLabel();
        hari92 = new javax.swing.JPanel();
        tanggal92 = new javax.swing.JLabel();
        hari93 = new javax.swing.JPanel();
        tanggal93 = new javax.swing.JLabel();
        hari94 = new javax.swing.JPanel();
        tanggal94 = new javax.swing.JLabel();
        hari95 = new javax.swing.JPanel();
        tanggal95 = new javax.swing.JLabel();
        Minggu = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        hari96 = new javax.swing.JPanel();
        tanggal96 = new javax.swing.JLabel();
        hari97 = new javax.swing.JPanel();
        tanggal97 = new javax.swing.JLabel();
        hari98 = new javax.swing.JPanel();
        tanggal98 = new javax.swing.JLabel();
        hari99 = new javax.swing.JPanel();
        tanggal99 = new javax.swing.JLabel();
        hari100 = new javax.swing.JPanel();
        tanggal100 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombolMundur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tombolMundurLayout = new javax.swing.GroupLayout(tombolMundur);
        tombolMundur.setLayout(tombolMundurLayout);
        tombolMundurLayout.setHorizontalGroup(
            tombolMundurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        tombolMundurLayout.setVerticalGroup(
            tombolMundurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tombolMaju.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tombolMaju.setToolTipText("");
        tombolMaju.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tombolMajuFocusGained(evt);
            }
        });

        javax.swing.GroupLayout tombolMajuLayout = new javax.swing.GroupLayout(tombolMaju);
        tombolMaju.setLayout(tombolMajuLayout);
        tombolMajuLayout.setHorizontalGroup(
            tombolMajuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        tombolMajuLayout.setVerticalGroup(
            tombolMajuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bulan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bulan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bulan.setText("April");

        tahun.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tahun.setText("2019");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(tombolMaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolMundur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tahun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bulan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(tombolMaju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolMundur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        kalenderUtama.setBackground(new java.awt.Color(204, 255, 255));
        kalenderUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        kalenderUtama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Senin");

        hari66.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal66.setText("1");

        javax.swing.GroupLayout hari66Layout = new javax.swing.GroupLayout(hari66);
        hari66.setLayout(hari66Layout);
        hari66Layout.setHorizontalGroup(
            hari66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari66Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal66)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari66Layout.setVerticalGroup(
            hari66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari66Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal66)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari67.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal67.setText("1");

        javax.swing.GroupLayout hari67Layout = new javax.swing.GroupLayout(hari67);
        hari67.setLayout(hari67Layout);
        hari67Layout.setHorizontalGroup(
            hari67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari67Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal67)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari67Layout.setVerticalGroup(
            hari67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari67Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal67)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari68.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal68.setText("1");

        javax.swing.GroupLayout hari68Layout = new javax.swing.GroupLayout(hari68);
        hari68.setLayout(hari68Layout);
        hari68Layout.setHorizontalGroup(
            hari68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal68)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari68Layout.setVerticalGroup(
            hari68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari68Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal68)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari69.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal69.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal69.setText("1");

        javax.swing.GroupLayout hari69Layout = new javax.swing.GroupLayout(hari69);
        hari69.setLayout(hari69Layout);
        hari69Layout.setHorizontalGroup(
            hari69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal69)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari69Layout.setVerticalGroup(
            hari69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal69)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari70.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal70.setText("1");

        javax.swing.GroupLayout hari70Layout = new javax.swing.GroupLayout(hari70);
        hari70.setLayout(hari70Layout);
        hari70Layout.setHorizontalGroup(
            hari70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari70Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal70)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari70Layout.setVerticalGroup(
            hari70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari70Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal70)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SeninLayout = new javax.swing.GroupLayout(Senin);
        Senin.setLayout(SeninLayout);
        SeninLayout.setHorizontalGroup(
            SeninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SeninLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        SeninLayout.setVerticalGroup(
            SeninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeninLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Selasa");

        hari71.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal71.setText("1");

        javax.swing.GroupLayout hari71Layout = new javax.swing.GroupLayout(hari71);
        hari71.setLayout(hari71Layout);
        hari71Layout.setHorizontalGroup(
            hari71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal71)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari71Layout.setVerticalGroup(
            hari71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal71)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari72.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal72.setText("1");

        javax.swing.GroupLayout hari72Layout = new javax.swing.GroupLayout(hari72);
        hari72.setLayout(hari72Layout);
        hari72Layout.setHorizontalGroup(
            hari72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal72)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari72Layout.setVerticalGroup(
            hari72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari72Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal72)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari73.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal73.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal73.setText("1");

        javax.swing.GroupLayout hari73Layout = new javax.swing.GroupLayout(hari73);
        hari73.setLayout(hari73Layout);
        hari73Layout.setHorizontalGroup(
            hari73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal73)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari73Layout.setVerticalGroup(
            hari73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal73)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari74.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal74.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal74.setText("1");

        javax.swing.GroupLayout hari74Layout = new javax.swing.GroupLayout(hari74);
        hari74.setLayout(hari74Layout);
        hari74Layout.setHorizontalGroup(
            hari74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal74)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari74Layout.setVerticalGroup(
            hari74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari74Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal74)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari75.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal75.setText("1");

        javax.swing.GroupLayout hari75Layout = new javax.swing.GroupLayout(hari75);
        hari75.setLayout(hari75Layout);
        hari75Layout.setHorizontalGroup(
            hari75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal75)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari75Layout.setVerticalGroup(
            hari75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal75)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SelasaLayout = new javax.swing.GroupLayout(Selasa);
        Selasa.setLayout(SelasaLayout);
        SelasaLayout.setHorizontalGroup(
            SelasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SelasaLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        SelasaLayout.setVerticalGroup(
            SelasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelasaLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Rabu");

        hari76.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal76.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal76.setText("1");

        javax.swing.GroupLayout hari76Layout = new javax.swing.GroupLayout(hari76);
        hari76.setLayout(hari76Layout);
        hari76Layout.setHorizontalGroup(
            hari76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari76Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal76)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari76Layout.setVerticalGroup(
            hari76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari76Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal76)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari77.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal77.setText("1");

        javax.swing.GroupLayout hari77Layout = new javax.swing.GroupLayout(hari77);
        hari77.setLayout(hari77Layout);
        hari77Layout.setHorizontalGroup(
            hari77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari77Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal77)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari77Layout.setVerticalGroup(
            hari77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari77Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal77)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal78.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal78.setText("1");

        javax.swing.GroupLayout hari78Layout = new javax.swing.GroupLayout(hari78);
        hari78.setLayout(hari78Layout);
        hari78Layout.setHorizontalGroup(
            hari78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari78Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal78)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari78Layout.setVerticalGroup(
            hari78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari78Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal78)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari79.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal79.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal79.setText("1");

        javax.swing.GroupLayout hari79Layout = new javax.swing.GroupLayout(hari79);
        hari79.setLayout(hari79Layout);
        hari79Layout.setHorizontalGroup(
            hari79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari79Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal79)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari79Layout.setVerticalGroup(
            hari79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari79Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal79)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari80.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal80.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal80.setText("1");

        javax.swing.GroupLayout hari80Layout = new javax.swing.GroupLayout(hari80);
        hari80.setLayout(hari80Layout);
        hari80Layout.setHorizontalGroup(
            hari80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari80Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal80)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari80Layout.setVerticalGroup(
            hari80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari80Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal80)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RabuLayout = new javax.swing.GroupLayout(Rabu);
        Rabu.setLayout(RabuLayout);
        RabuLayout.setHorizontalGroup(
            RabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RabuLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        RabuLayout.setVerticalGroup(
            RabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RabuLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Kamis");

        hari81.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal81.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal81.setText("1");

        javax.swing.GroupLayout hari81Layout = new javax.swing.GroupLayout(hari81);
        hari81.setLayout(hari81Layout);
        hari81Layout.setHorizontalGroup(
            hari81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari81Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal81)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari81Layout.setVerticalGroup(
            hari81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari81Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal81)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari82.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal82.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal82.setText("1");

        javax.swing.GroupLayout hari82Layout = new javax.swing.GroupLayout(hari82);
        hari82.setLayout(hari82Layout);
        hari82Layout.setHorizontalGroup(
            hari82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari82Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal82)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari82Layout.setVerticalGroup(
            hari82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari82Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal82)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari83.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal83.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal83.setText("1");

        javax.swing.GroupLayout hari83Layout = new javax.swing.GroupLayout(hari83);
        hari83.setLayout(hari83Layout);
        hari83Layout.setHorizontalGroup(
            hari83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal83)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari83Layout.setVerticalGroup(
            hari83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari83Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal83)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari84.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal84.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal84.setText("1");

        javax.swing.GroupLayout hari84Layout = new javax.swing.GroupLayout(hari84);
        hari84.setLayout(hari84Layout);
        hari84Layout.setHorizontalGroup(
            hari84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari84Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal84)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari84Layout.setVerticalGroup(
            hari84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari84Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal84)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari85.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal85.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal85.setText("1");

        javax.swing.GroupLayout hari85Layout = new javax.swing.GroupLayout(hari85);
        hari85.setLayout(hari85Layout);
        hari85Layout.setHorizontalGroup(
            hari85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari85Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal85)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari85Layout.setVerticalGroup(
            hari85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari85Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal85)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KamisLayout = new javax.swing.GroupLayout(Kamis);
        Kamis.setLayout(KamisLayout);
        KamisLayout.setHorizontalGroup(
            KamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(KamisLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        KamisLayout.setVerticalGroup(
            KamisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KamisLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Jumat");

        hari86.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal86.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal86.setText("1");

        javax.swing.GroupLayout hari86Layout = new javax.swing.GroupLayout(hari86);
        hari86.setLayout(hari86Layout);
        hari86Layout.setHorizontalGroup(
            hari86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal86)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari86Layout.setVerticalGroup(
            hari86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal86)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        hari87.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal87.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal87.setText("1");

        javax.swing.GroupLayout hari87Layout = new javax.swing.GroupLayout(hari87);
        hari87.setLayout(hari87Layout);
        hari87Layout.setHorizontalGroup(
            hari87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari87Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal87)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari87Layout.setVerticalGroup(
            hari87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari87Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal87)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        hari88.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal88.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal88.setText("1");

        javax.swing.GroupLayout hari88Layout = new javax.swing.GroupLayout(hari88);
        hari88.setLayout(hari88Layout);
        hari88Layout.setHorizontalGroup(
            hari88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari88Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal88)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari88Layout.setVerticalGroup(
            hari88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari88Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal88)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        hari89.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal89.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal89.setText("1");

        javax.swing.GroupLayout hari89Layout = new javax.swing.GroupLayout(hari89);
        hari89.setLayout(hari89Layout);
        hari89Layout.setHorizontalGroup(
            hari89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari89Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal89)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari89Layout.setVerticalGroup(
            hari89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari89Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal89)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        hari90.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal90.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal90.setText("1");

        javax.swing.GroupLayout hari90Layout = new javax.swing.GroupLayout(hari90);
        hari90.setLayout(hari90Layout);
        hari90Layout.setHorizontalGroup(
            hari90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari90Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal90)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari90Layout.setVerticalGroup(
            hari90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari90Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal90)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JumatLayout = new javax.swing.GroupLayout(Jumat);
        Jumat.setLayout(JumatLayout);
        JumatLayout.setHorizontalGroup(
            JumatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JumatLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        JumatLayout.setVerticalGroup(
            JumatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JumatLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Sabtu");

        hari91.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal91.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal91.setText("1");

        javax.swing.GroupLayout hari91Layout = new javax.swing.GroupLayout(hari91);
        hari91.setLayout(hari91Layout);
        hari91Layout.setHorizontalGroup(
            hari91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal91)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari91Layout.setVerticalGroup(
            hari91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal91)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari92.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal92.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal92.setText("1");

        javax.swing.GroupLayout hari92Layout = new javax.swing.GroupLayout(hari92);
        hari92.setLayout(hari92Layout);
        hari92Layout.setHorizontalGroup(
            hari92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari92Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal92)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari92Layout.setVerticalGroup(
            hari92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari92Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal92)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari93.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal93.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal93.setText("1");

        javax.swing.GroupLayout hari93Layout = new javax.swing.GroupLayout(hari93);
        hari93.setLayout(hari93Layout);
        hari93Layout.setHorizontalGroup(
            hari93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari93Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal93)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari93Layout.setVerticalGroup(
            hari93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari93Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal93)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari94.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal94.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal94.setText("1");

        javax.swing.GroupLayout hari94Layout = new javax.swing.GroupLayout(hari94);
        hari94.setLayout(hari94Layout);
        hari94Layout.setHorizontalGroup(
            hari94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari94Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal94)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari94Layout.setVerticalGroup(
            hari94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari94Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal94)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari95.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal95.setText("1");

        javax.swing.GroupLayout hari95Layout = new javax.swing.GroupLayout(hari95);
        hari95.setLayout(hari95Layout);
        hari95Layout.setHorizontalGroup(
            hari95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari95Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal95)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari95Layout.setVerticalGroup(
            hari95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari95Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal95)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SabtuLayout = new javax.swing.GroupLayout(Sabtu);
        Sabtu.setLayout(SabtuLayout);
        SabtuLayout.setHorizontalGroup(
            SabtuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SabtuLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        SabtuLayout.setVerticalGroup(
            SabtuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SabtuLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Minggu");

        hari96.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal96.setText("1");

        javax.swing.GroupLayout hari96Layout = new javax.swing.GroupLayout(hari96);
        hari96.setLayout(hari96Layout);
        hari96Layout.setHorizontalGroup(
            hari96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari96Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal96)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari96Layout.setVerticalGroup(
            hari96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari96Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal96)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari97.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal97.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal97.setText("1");

        javax.swing.GroupLayout hari97Layout = new javax.swing.GroupLayout(hari97);
        hari97.setLayout(hari97Layout);
        hari97Layout.setHorizontalGroup(
            hari97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari97Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal97)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari97Layout.setVerticalGroup(
            hari97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari97Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal97)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari98.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal98.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal98.setText("1");

        javax.swing.GroupLayout hari98Layout = new javax.swing.GroupLayout(hari98);
        hari98.setLayout(hari98Layout);
        hari98Layout.setHorizontalGroup(
            hari98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari98Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal98)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari98Layout.setVerticalGroup(
            hari98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari98Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal98)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari99.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal99.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal99.setText("1");

        javax.swing.GroupLayout hari99Layout = new javax.swing.GroupLayout(hari99);
        hari99.setLayout(hari99Layout);
        hari99Layout.setHorizontalGroup(
            hari99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari99Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal99)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari99Layout.setVerticalGroup(
            hari99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari99Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal99)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hari100.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggal100.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal100.setText("1");

        javax.swing.GroupLayout hari100Layout = new javax.swing.GroupLayout(hari100);
        hari100.setLayout(hari100Layout);
        hari100Layout.setHorizontalGroup(
            hari100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal100)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hari100Layout.setVerticalGroup(
            hari100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hari100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal100)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MingguLayout = new javax.swing.GroupLayout(Minggu);
        Minggu.setLayout(MingguLayout);
        MingguLayout.setHorizontalGroup(
            MingguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hari96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hari100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MingguLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        MingguLayout.setVerticalGroup(
            MingguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MingguLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hari100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kalenderUtamaLayout = new javax.swing.GroupLayout(kalenderUtama);
        kalenderUtama.setLayout(kalenderUtamaLayout);
        kalenderUtamaLayout.setHorizontalGroup(
            kalenderUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalenderUtamaLayout.createSequentialGroup()
                .addComponent(Senin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rabu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kamis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jumat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sabtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minggu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        kalenderUtamaLayout.setVerticalGroup(
            kalenderUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jumat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Sabtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Minggu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Kamis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Rabu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Senin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Selasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout KalenderTamuLayout = new javax.swing.GroupLayout(KalenderTamu);
        KalenderTamu.setLayout(KalenderTamuLayout);
        KalenderTamuLayout.setHorizontalGroup(
            KalenderTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KalenderTamuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KalenderTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kalenderUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        KalenderTamuLayout.setVerticalGroup(
            KalenderTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KalenderTamuLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(kalenderUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(KalenderTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(KalenderTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolMajuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tombolMajuFocusGained
        // TODO add your handlng code here:
    }//GEN-LAST:event_tombolMajuFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingTamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingTamu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jumat;
    private javax.swing.JPanel KalenderTamu;
    private javax.swing.JPanel Kamis;
    private javax.swing.JPanel Minggu;
    private javax.swing.JPanel Rabu;
    private javax.swing.JPanel Sabtu;
    private javax.swing.JPanel Selasa;
    private javax.swing.JPanel Senin;
    private javax.swing.JLabel bulan;
    private javax.swing.JPanel hari100;
    private javax.swing.JPanel hari66;
    private javax.swing.JPanel hari67;
    private javax.swing.JPanel hari68;
    private javax.swing.JPanel hari69;
    private javax.swing.JPanel hari70;
    private javax.swing.JPanel hari71;
    private javax.swing.JPanel hari72;
    private javax.swing.JPanel hari73;
    private javax.swing.JPanel hari74;
    private javax.swing.JPanel hari75;
    private javax.swing.JPanel hari76;
    private javax.swing.JPanel hari77;
    private javax.swing.JPanel hari78;
    private javax.swing.JPanel hari79;
    private javax.swing.JPanel hari80;
    private javax.swing.JPanel hari81;
    private javax.swing.JPanel hari82;
    private javax.swing.JPanel hari83;
    private javax.swing.JPanel hari84;
    private javax.swing.JPanel hari85;
    private javax.swing.JPanel hari86;
    private javax.swing.JPanel hari87;
    private javax.swing.JPanel hari88;
    private javax.swing.JPanel hari89;
    private javax.swing.JPanel hari90;
    private javax.swing.JPanel hari91;
    private javax.swing.JPanel hari92;
    private javax.swing.JPanel hari93;
    private javax.swing.JPanel hari94;
    private javax.swing.JPanel hari95;
    private javax.swing.JPanel hari96;
    private javax.swing.JPanel hari97;
    private javax.swing.JPanel hari98;
    private javax.swing.JPanel hari99;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel kalenderUtama;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel tanggal100;
    private javax.swing.JLabel tanggal66;
    private javax.swing.JLabel tanggal67;
    private javax.swing.JLabel tanggal68;
    private javax.swing.JLabel tanggal69;
    private javax.swing.JLabel tanggal70;
    private javax.swing.JLabel tanggal71;
    private javax.swing.JLabel tanggal72;
    private javax.swing.JLabel tanggal73;
    private javax.swing.JLabel tanggal74;
    private javax.swing.JLabel tanggal75;
    private javax.swing.JLabel tanggal76;
    private javax.swing.JLabel tanggal77;
    private javax.swing.JLabel tanggal78;
    private javax.swing.JLabel tanggal79;
    private javax.swing.JLabel tanggal80;
    private javax.swing.JLabel tanggal81;
    private javax.swing.JLabel tanggal82;
    private javax.swing.JLabel tanggal83;
    private javax.swing.JLabel tanggal84;
    private javax.swing.JLabel tanggal85;
    private javax.swing.JLabel tanggal86;
    private javax.swing.JLabel tanggal87;
    private javax.swing.JLabel tanggal88;
    private javax.swing.JLabel tanggal89;
    private javax.swing.JLabel tanggal90;
    private javax.swing.JLabel tanggal91;
    private javax.swing.JLabel tanggal92;
    private javax.swing.JLabel tanggal93;
    private javax.swing.JLabel tanggal94;
    private javax.swing.JLabel tanggal95;
    private javax.swing.JLabel tanggal96;
    private javax.swing.JLabel tanggal97;
    private javax.swing.JLabel tanggal98;
    private javax.swing.JLabel tanggal99;
    private javax.swing.JPanel tombolMaju;
    private javax.swing.JPanel tombolMundur;
    // End of variables declaration//GEN-END:variables
}
