/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siakkam;

/**
 *
 * @author lenovo
 */
public class userAdminMaster extends javax.swing.JFrame {

    
    
    // Variables declaration - do not modify                     
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel  panelKalender;
    private javax.swing.JButton tombolHapusJadwal;
    private javax.swing.JButton tombolKeluar;
    private javax.swing.JButton tombolNotifikasi;
    private javax.swing.JButton tombolTambahJadwal;
    private kalenderKu.kalender Kalender;
    javax.swing.JFrame parent;
    String username="";
    // End of variables declaration              
    /**
     * Creates new form user
     */
    public userAdminMaster(javax.swing.JFrame parent, String username) {
        this.username = username;
        this.parent = parent;
        initComponents();
        this.setTitle("Selamat Datang Admin "+username);
        this.setSize(800, 800);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelBawah = new javax.swing.JPanel();
        tombolHapusJadwal = new javax.swing.JButton();
        tombolTambahJadwal = new javax.swing.JButton();
        tombolNotifikasi = new javax.swing.JButton();
        tombolKeluar = new javax.swing.JButton();
        panelKalender = new javax.swing.JPanel();
        Kalender = new kalenderKu.kalender();

        tombolHapusJadwal.setBackground(new java.awt.Color(0, 102, 102));
        tombolHapusJadwal.setText("Menghapus Jadwal");
        tombolHapusJadwal.setPreferredSize(new java.awt.Dimension(125, 23));
        tombolHapusJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolHapusJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahJadwalActionPerformed(evt);
            }
        });

        tombolTambahJadwal.setBackground(new java.awt.Color(0, 102, 102));
        tombolTambahJadwal.setText("Menyetujui Pengajuan");
        tombolTambahJadwal.setPreferredSize(new java.awt.Dimension(125, 23));
        tombolTambahJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolTambahJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menyetujuiPengajuan(evt);
            }
        });

        tombolNotifikasi.setBackground(new java.awt.Color(0, 102, 102));
        tombolNotifikasi.setText("Notifikasi");
        tombolNotifikasi.setPreferredSize(new java.awt.Dimension(125, 23));
        tombolNotifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolNotifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolNotifikasiActionPerformed(evt);
            }
        });

        tombolKeluar.setBackground(new java.awt.Color(0, 102, 102));
        tombolKeluar.setText("Keluar");
        tombolKeluar.setPreferredSize(new java.awt.Dimension(125, 23));
        tombolKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBawahLayout = new javax.swing.GroupLayout(panelBawah);
        panelBawah.setLayout(panelBawahLayout);
        panelBawahLayout.setHorizontalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolHapusJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolTambahJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolNotifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBawahLayout.setVerticalGroup(
            panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolTambahJadwal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolHapusJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolNotifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKalenderLayout = new javax.swing.GroupLayout(panelKalender);
        panelKalender.setLayout(panelKalenderLayout);
        panelKalenderLayout.setHorizontalGroup(
            panelKalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kalender)
        );
        panelKalenderLayout.setVerticalGroup(
            panelKalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kalender)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelKalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tombolTambahJadwalActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        this.setVisible(false);
        new hapusJadwal(this).setVisible(true);
    }                                                  

    private void tombolNotifikasiActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }    
    
    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {  
        parent.setVisible(true);
        this.dispose();
    }    
    private void menyetujuiPengajuan(java.awt.event.ActionEvent evt){
        this.setVisible(false);
        new setujuiPengajuan(this).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userAdminMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userAdminMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userAdminMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userAdminMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userAdminMaster frame = new userAdminMaster(null, null);
                frame.setTitle("Selamat Datang Admin Utama");
                frame.setSize(800, 800);
                frame.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }
     
}
